### ISSUE TITLE
Suggestion: Remove all "running test $TEST" statements

### ISSUE THREAD

**Issue by ALobsterDog** [JakeCover/distest#13]
the discord.py library gives us sane rate handling, blessed be to Danny. So this means that if a bot is spamming the library holds onto its messages so it doesn't get denied by discord. Therefore every message we send that isn't a test during a ``--run all`` reduces test throughput.

the "running test.." messages cut our test throughput in half, doubling the amount of time it takes to run a full suite.

I propose we hotfix this in, it would take the removal of only a couple lines.

**Comment by ALobsterDog** [comment]
I opened a pr #14 that pushes this to master branch. But you can just use that as a blueprint and remove those four lines in whatever branch you think is appropriate.

**Comment by JakeCover** [comment]
That sounds great, I hadn't thought of that. I'll take a look!

**Comment by ALobsterDog** [comment]
I'm gonna just go ahead integrate this change in feature/refactor_modules and it will get added in when we push to master, as I imagine we aren't far from the next release.
