### ISSUE TITLE
Implement Timeout when run Interactively

### ISSUE THREAD

**Issue by JakeCover** [JakeCover/distest#23]
We pass the optional timeout from the command line into interactive, but it never actually makes it to where it needs to go. Most of the code should be the same as in the CLI mode, we just need to copy it over. See below for the dead end: 

https://github.com/JakeCover/distest/blob/ccd3b63e78defb34e93586fed71139efa30a2b8d/distest/__init__.py#L114-L128

We need to:
- [x] Cascade `timeout` further down
- [x] Test manually, as the CI/CD won't test interactive-only features yet (needs to also be added eventually)

Notes: brought up when documenting for #21, possible 1.1 item

**Comment by ALobsterDog** [comment]
@JakeCover I already implemented this, I just forgot to pass the parameter to the `DiscordInteractiveInterface` constructor call. pushed to documentation branch.
