### ISSUE TITLE
README.md Documentation Out of Date

### ISSUE THREAD

**Issue by cmd-drake** [JakeCover/distest#29]
The documentation in README.me for setup, and running distest is currently out of date as of Commit  84ea6220016bfe9f38ba9d82f7496e7f7cbef8c9. The CLI no longer accepts BOTNAME for starting the tests, but instead requires a BotID.

**Comment by JakeCover** [comment]
Good catch! I'll fix it tomorrow. Thanks!

**Comment by vintprox** [comment]
Um, it doesn't seem fixed.

**Comment by JakeCover** [comment]
Finally got around to this one too!
