### ISSUE TITLE
Suggestion: Refactor __init__.py into separate modules

### ISSUE THREAD

**Issue by ALobsterDog** [JakeCover/distest#3]
I believe most if not all of the classes in ``__init__.py`` should be in their own files to make the code easier to work with. I would be willing to take on this refactor but obviously won't without a greenlight from @JakeCover

**Comment by JakeCover** [comment]
For sure, if you can do it and still make the package work. I know it's possible, but I don't have enough experience myself. If you can do it, go ahead!

**Comment by ALobsterDog** [comment]
sure thing i'll set to working on it this weekend.

**Comment by JakeCover** [comment]
Ok, the Refactor is done as of #5 being committed. Great job!

**Comment by JakeCover** [comment]
With your agreement, I'll close this issue

**Comment by JakeCover** [comment]
Actually, can you write a blurb about how the new code structure works, and what now lives in each file? This would be really useful to make sure we know what to add to each file. IMO a docstring at the top of each new file should work great, just a short paragraph is fine.

**Comment by ALobsterDog** [comment]
Sure I can bang that out right now.

**Comment by ALobsterDog** [comment]
Closing this since the refactor is complete and pushed to master.
