### ISSUE TITLE
Error: Looks like the target bot is on the server but offline, you might want to check on that!

### ISSUE THREAD

**Issue by johnsturgeon** [JakeCover/distest#37]
Not sure why I'm getting that error message, since my bot is most definitely online, and the test passed.

**Comment by JakeCover** [comment]
Not totally sure, but this sounds related to #31 and #32 about privileged intents. Can you go onto the discord developer portal and enable the member access privileged intents? Should be info about it here. https://discordpy.readthedocs.io/en/latest/intents.html#where-d-my-members-go

Let me know if that works or not!

**Comment by johnsturgeon** [comment]
Will do!  I have a couple other issues, atm but I'll get to that before the weekend is up.

**Comment by johnsturgeon** [comment]
I think it might have been a hiccup w/discord, because all my test scripts are running fine today, let's go ahead and close this one out

**Comment by JakeCover** [comment]
Strange! Hope it doesn't come back again.
