### ISSUE TITLE
validate_discord_token.py regex parser is outdated

### ISSUE THREAD

**Issue by sean-keisuke** [JakeCover/distest#45]
```
if not re.match(r"[MN][A-Za-z\d]{23}\.[\w-]{6}\.[\w-]{27}", token_value):
```
only allows tokens with prefix M or N. Current Discord tokens may provide new tokens that start with letter O.

**Comment by sean-keisuke** [comment]
> ```
> if not re.match(r"[MN][A-Za-z\d]{23}\.[\w-]{6}\.[\w-]{27}", token_value):
> ```
> 
> only allows tokens with prefix M or N. Current Discord tokens may provide new tokens that start with letter O.

<img width="669" alt="Screen Shot 2021-02-16 at 7 55 00 PM" src="https://user-images.githubusercontent.com/45245505/108150139-657a1300-7091-11eb-83e2-ae5f79a80043.png">

**Comment by JakeCover** [comment]
#47
