### ISSUE TITLE
Verify each test and add to `example_tests.py`

### ISSUE THREAD

**Issue by JakeCover** [JakeCover/distest#6]
- [x] send_message
    - [x] edit_message
    - [x] wait_for_reaction
    - [x] wait_for_message
    - [x] wait_for_reply
    - [x] assert_message_equals
    - [x] assert_message_contains
    - [x] assert_message_matches
    - [x] assert_reply_equals
    - [x] assert_reply_contains
    - [x] assert_reply_matches
    - [x] assert_reaction_equals
    - [x] ensure_silence
    - [x] ask_human

**Comment by ALobsterDog** [comment]
Since all of the ``assert_reply_x`` functions use their complementary ``assert_message_x`` function, I think that using ``reply`` counts as testing ``message.`` Does that make sense? I also can think of no clever way to test these functions within the example modules.

**Comment by JakeCover** [comment]
You could write a test function that calls `send_message()` and `assert_message_x()` and basically build our own `assert_reply_x()` for testing. They exist basically because they can (we need them anyway, so let's expose them) and because it lets you do custom things if you need. We really don't need to test the message assertions, like you said they are covered by the reply assertions, but we might want to just have them as examples and leave them commented out or something. I need to check, but the waits should also be covered. 

Also question: can u check my checkboxes?

**Comment by ALobsterDog** [comment]
I just tested and yes, I can edit your checkboxes.

**Comment by JakeCover** [comment]
Updated the checklist to match what my coverage test told me was being run/not run. I'll hold off on this until #19 is done though, since that may change the way the interface functions are actually called.

**Comment by JakeCover** [comment]
Ok I think this is done as of the latest commit to #20. I'll close this when I close that shortly.
