### ISSUE TITLE
Test the new refactored files with pip

### ISSUE THREAD

**Issue by JakeCover** [JakeCover/distest#7]
As changed in #5, the project's Filesystem has been refactored to make the files more clear (still in a feature branch ba3b311a00837f97baaa389b0e2ec2c75e1711b5, needs testing be tested before this enters develop). This issue is about testing the changes before they enter develop.

**Comment by ALobsterDog** [comment]
@JakeCover I installed the the latest commit of feature/refactor_modules as a pip package in a virtual environment, everything seemed to work perfectly. Can I get you to do the same (with commit 9bb60e736310aabe49dac1fb3cb16c4ada40c751)? I can't see why it wouldn't work, and if it does we should go ahead and merge the branch into develop so we can start working on *real* features. the refactored code will be a lot easier to work with.

**Comment by ALobsterDog** [comment]
As a side note, I've actually been using the library as a pip package this whole time. you can use `pip install -e .` when in the project's top folder and it will install the package as a reference to the source files, so it's constantly updated when you change the files. That way you don't have to reinstall every time you make a change.

**Comment by JakeCover** [comment]
That I did figure out from packaging guides, it works for me. I would like to test the CI/CD on this, if it works and this passes then I can finish the feature and we can make a release.

**Comment by ALobsterDog** [comment]
Great! keep me posted.

**Comment by ALobsterDog** [comment]
@JakeCover I see you got us up and running on PyPi. Great! I'll close this issue.
